### ISSUE TITLE
Loading and editing of supplied test content

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#10]
George/Dan.

Mary supplying content ASAP, may need editing for mobile/web.

**Comment by rek** [comment]
When there is some content, please let me know, we should put it in the wiki here (https://github.com/beak-lab/swell/wiki). The sooner the better.

**Comment by grgcnnr** [comment]
See 
https://github.com/beak-lab/swell/wiki/Prototype-Challenge-content
https://github.com/beak-lab/swell/wiki/List-of-top-level-domains
https://github.com/beak-lab/swell/wiki/List-of-work-domain-challenges
