### ISSUE TITLE
Collection and collation of user feedback

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#13]
Yeah, as the title suggests, is an 'in app' feedback mechanism achievable in this sprint?

**Comment by rek** [comment]
You mean a comments form? What is this for? Who would use it?

It is for people who will be testing this release to report back about their experience?
Or is it for real users to do something?

**Comment by drichardson23** [comment]
Discussed briefly last week, I think we can consider 'in app' feedback out of scope ATM.

However, we'll need to decide upon a mechanism for collecting feedback from test users once prototype is launched.

**Comment by grgcnnr** [comment]
Now hang on a minute. I thought this was just a demo tool. are people actually going to be using it?

**Comment by drichardson23** [comment]
I'm not being clear here. As the prototype is demo'd there will be feedback from the demo presenter and audience. Will need a mechanism to capture their feedback - this is not a technical or design task. A Google form should suffice.

**Comment by grgcnnr** [comment]
Gotcha, soz

**Comment by grgcnnr** [comment]
Gotcha soz

**Comment by grgcnnr** [comment]
in answer to original question... No :)

The app will never be use unsupervised.
