### ISSUE TITLE
Public or private source hosting

### ISSUE THREAD

**Issue by rek** [beak-lab/swell#15]
It is an issue we are hosting this source code in public? or should we use a private repo?

What licence is this work to be done under? It is to be open source? MIT?

**Comment by drichardson23** [comment]
Sup y'all.

I guess it depends on the lady paying the bill?

George - thoughts?

**Comment by grgcnnr** [comment]
rekon its fine for prototype. flag it as a discussion point for the real build

**Comment by rek** [comment]
just clear it with mary. as she is the owner of the work we produce i
assume.

**Comment by grgcnnr** [comment]
Will do
