### ISSUE TITLE
Short description of each challenge

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#17]
For the home screen, each challenge needs a few words describing it.

**Comment by drichardson23** [comment]
OK, use placeholder if you need to. We can ask Mary for text.

**Comment by drichardson23** [comment]
Notified Mary

**Comment by drichardson23** [comment]
Try these:

Words for each challenge on home screen

Discovering and using my talents

Continuing my education

Finding a job after a period of unemployment

Deciding to disclose my lived experience to an employer (slight word change)

Negotiating work conditions related to my distress (slight word change – as a related challenge)

Dealing with anticipated discrimination (slight word change – as a related challenge)

Keeping my job
