### ISSUE TITLE
Some sample tasks

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#18]
Need to make up some goals that the prototype user might have set in the past around each challenge. 

Seeing as we're mocking up a work challenge they could all be from this domain.

**Comment by drichardson23** [comment]
OK, do we want Mary to supply this content?

**Comment by grgcnnr** [comment]
Yes please

**Comment by drichardson23** [comment]
OK notified her

**Comment by drichardson23** [comment]
Try these:

Examples of goals users might have set in the past:

I will never disclose

I will disclose if my distress is starting to interfere with my work

I will disclose only after I have been offered a job
