### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#2]
Ok, so what is this thing going to look like?

Grg - do you have a link for the wireframes?

**Comment by rek** [comment]
Look in the google drive shared folder.

**Comment by grgcnnr** [comment]
Beyond wireframes. I have no idea at this stage.

I need to do some style tiles or something

**Comment by grgcnnr** [comment]
Concepts will become available in the alpha designs folder of step 7 as they progress.

https://drive.google.com/folderview?id=0B-OD4tsu4vreMlJid3VIaFhXeFE&usp=sharing

**Comment by drichardson23** [comment]
These designs are pretty sweet huh

**Comment by grgcnnr** [comment]
they're ok - the actual app isn't quite as flash :)
