### ISSUE TITLE
Google play developer account

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#21]
Set up a play developer acct https://play.google.com/apps/publish/signup/

maybe with a new google account

**Comment by drichardson23** [comment]
Want me to handle this?

**Comment by grgcnnr** [comment]
Just flagging as a need to do this week. What do you think is the best way of doing it? Create a new google acct?

**Comment by rek** [comment]
make a beak lab account to release the project from?

**Comment by drichardson23** [comment]
set up
