### ISSUE TITLE
Challenges landing page

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#22]
I.E. the page you get after clicking 'Work'.

Should there be some intro text on this page to explain the choices to the user?

**Comment by grgcnnr** [comment]
yes there should.
Was there anything in that stuff that mary sent that might be appropriate

**Comment by drichardson23** [comment]
I'll have a hunt around

**Comment by drichardson23** [comment]
Couldn't find anything general enough - have requested from Mary.
