### ISSUE TITLE
'My Stuff' tab

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#23]
What is envisaged going on this tab?

**Comment by grgcnnr** [comment]
Giant question mark. :)

One day: fave'd resources, activity related goals activity related communications, stats about activity completes

**Comment by drichardson23** [comment]
OK, lets mock this up (in app) if time allows....

**Comment by rek** [comment]
My stuff is now quite populated. The question around this for now has been closed. Though the implementation remains.
