### ISSUE TITLE
Regarding resources

### ISSUE THREAD

**Issue by rek** [beak-lab/swell#25]
I think all resources should be stored externally on our domain or even on youtube. As opposed to packing them in the app.

App's can only be a certain size, though you can use expansion app's, but i think it might be better to offload? Is this an issue with IP of the videos etc?

**Comment by grgcnnr** [comment]
Agreed. For the demo there will only be one though so thought it would be OK to keep it on app. Will make it a shorter vid too

**Comment by rek** [comment]
ah ok sweet.
