### ISSUE TITLE
Swiping

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#30]
Not sure if it's a limitation of my device but in app there's no indication that I can swipe left (for profile) or right (for goals), might be worth adding a small tab or arrow in to indicate this? What do you think?

**Comment by grgcnnr** [comment]
Yeah agree. will probably need some sort of orientation in the real app (or just better design)

**Comment by drichardson23** [comment]
`still broken`

**Comment by drichardson23** [comment]
Actually don’t worry. User issue.
