### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#4]
OK dudes. Had a chat to Mary - we have a firm deadline of Monday 7 May to deliver a prototype.

I'm thinking a two week sprint starting Monday 23 June.

Can you guys confirm that you're OK with this?

Will need a daily stand up (via Google Hangouts) at 9am each day of the sprint, doable for you?

**Comment by grgcnnr** [comment]
Yeah that sounds perfect.

**Comment by drichardson23** [comment]
Cool, some tasty nuggets to chew over, here's what we're going to deliver:
1. Further scoping effort to refine exact requirements for each app interaction and development of robust ‘user stories’
2. Development of page templates, with appropriate styling of each page element
3. Development and implementation of rudimentary navigation system based on domain/challenge/activity paradigm
4. Development and implementation of limited activity functionality
5. Development and implementation of limited user profile page
6. Loading and editing of supplied test content
7. Packaging of app for Android operating system
8. Associated design work
9. Collection and collation of user feedback

Each one of these will get it's own issue.

**Comment by rek** [comment]
Excellent. Those are good master tickets, can we please get some sub tickets below each of them with what exactly is to be done.

**Comment by rek** [comment]
Sub tickets created. Please refer to them. Closing.
