### ISSUE TITLE
Content changes

### ISSUE THREAD

**Issue by maryohagan** [beak-lab/swell#44]
[Tab]
My stuff tab doesn't tap through to my stuff page

~~ 
[First activity page]
Activity 1: Pros and cons
Delete preamable after activity title and before ' What are the pros and cons...?'
Replace cross and tick with Pros and Cons
~~

[Next Page]
~~Activity 2: When to disclose [change title]~~

~~ 
When should I disclose (if at all)? [put ? at end]

I believe my distress will interfere with my ability to do the job
Disclose before they decide to employ you

I want to negotiate work conditions related to my distress
Disclose just after they offer you the job

I want to let my employer know when I'm struggling
Disclose when you start struggling - don't wait too long

My lived experience has no impact on my work
No need to disclose
~~

[Next Page]
Activity 3: Positive disclosure
[Include this preamble] When you disclose don't be negative or apologetic. Turn it into an opportunity to sell your strengths.
Place 'make it positive by explaining' Inside paper

[Next Page]
Activity 3 [not 2]

[Next Page]
Activity 3 [not 2]

[Next Page]
Activity 3 [not 2]

[Next Page]
Now lets set goals or record your decision about disclosure to employers

[can the box expand as I type? Can I set more than one goal?]

Add underneath goal: This will be added to your work goals page.

[Next Page]
[Will recent goals and activity history go through to anything - if not are they necessary since they are included in left hand swipe]

[What are the progress buttons at the bottom?]

[Additional content to include]
Can you add to the prototype somewhere:

Rate the disclosure activity [use a slider?]

Try these related work challenges:
Negotiating work conditions related to my distress 
Dealing with anticipated discrimination 

Go to the disclosure resources page for more info.

Go to your my stuff to look at your goals

**Comment by grgcnnr** [comment]
wow big ticket :)

**Comment by grgcnnr** [comment]
~~[First activity page]
Activity 1: Pros and cons
Delete preamable after activity title and before ' What are the pros and cons...?'
Replace cross and tick with Pros and Cons~~
