### ISSUE TITLE
Back arrow on bottom of page

### ISSUE THREAD

**Issue by maryohagan** [beak-lab/swell#60]
Doesn't work

**Comment by grgcnnr** [comment]
elaborate please? which page? what are you doing to it?

**Comment by maryohagan** [comment]
When press on blue arrow and it goes brown and i tap on it it goes forward not backward

**Comment by grgcnnr** [comment]
ah yes. @rek sometimes onunpressed doesn't seem to fire. maybe if a tab is detected while the button is still in its back state we can manually fire the back event.

Sorry. i know this is kinda in my area :+1:

**Comment by rek** [comment]
seems ok, plz test. cannot reproduce.

**Comment by grgcnnr** [comment]
Confirmed and awesome
