### ISSUE TITLE
Page headed Recent goals

### ISSUE THREAD

**Issue by maryohagan** [beak-lab/swell#64]
Add 'add goal' to new work goals page

**Comment by grgcnnr** [comment]
To elaborate: a page that lists goals aggregated from all challenges in a domain.
So the work domain will have a work goals page rather than having this on the challenge's mystuff page.

I think that's what this is about? @maryohagan ?

**Comment by grgcnnr** [comment]
This ticke depends on #67

**Comment by maryohagan** [comment]
Yeah – does this need a response from me?
