### ISSUE TITLE
My stuff and work stuff

### ISSUE THREAD

**Issue by maryohagan** [beak-lab/swell#68]
Call 'My Stuff' in work challenge 'work stuff' to stop confusion with 'my stuff' side swipe page

**Comment by grgcnnr** [comment]
I think this would be better called 'progress' or something like that. It's not really work stuff  - its stuff related to this challenge. thoughts on this @maryohagan ?

**Comment by grgcnnr** [comment]
th

**Comment by maryohagan** [comment]
Ok work progress

**Comment by grgcnnr** [comment]
but what if you're not in a work challenge? then work progress makes no sense?

**Comment by maryohagan** [comment]
I assujmed you would call it some other sort of progress in another domain eg in the lifestyle domain wed call it lifestyle progress

**Comment by grgcnnr** [comment]
fair enough i guess.
