### ISSUE TITLE
Development and implementation of rudimentary navigation system based on domain/challenge/activity paradigm

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#7]
Let's cover this off during the kick off.

**Comment by rek** [comment]
Ok I think I have this sorted. We need hosting some where so we can share our progress with you.

**Comment by rek** [comment]
@grgcnnr

**Comment by grgcnnr** [comment]
http://www.swell.beak.co.nz/

**Comment by grgcnnr** [comment]
gimme your key

**Comment by drichardson23** [comment]
KEY PARTY!

**Comment by rek** [comment]
Done. Site is hosted, nav is working.
