### ISSUE TITLE
Development and implementation of limited activity functionality

### ISSUE THREAD

**Issue by drichardson23** [beak-lab/swell#8]
'Limited' needs to be defined.

Adam - lead.

**Comment by rek** [comment]
Pleases define and attach sub tickets.

**Comment by drichardson23** [comment]
OK, so Mary has suggested fridge magnets, lets discuss in Skype call tomorrow am

**Comment by rek** [comment]
we can start with that, but we might be able to implement sliders and
sorting too.

**Comment by rek** [comment]
Implemented 4 activities. Please make new tickets for any improvements on them.
