### ISSUE TITLE
Take away the white sheet explaining positive disclosure

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#89]
Not sure I like this white sheet – is there a good reason not to put it on the coloured background and just run it as a new para after the top para?

re: https://docs.google.com/presentation/d/1m_iCCSA1x1ebMn_NdwDrdDwSu-ObfTupuXqumzO392I/edit#slide=id.p21

**Comment by grgcnnr** [comment]
Basically, it's a design decision. 
I think that much text on a coloured background is fatiguing to read and I wanted to make sure it was visually separated from the activity description

**Comment by maryohagan** [comment]
OK lets leave it as is
