### ISSUE TITLE
Why is the arrow green now and not blue?

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#91]
re: https://docs.google.com/presentation/d/1m_iCCSA1x1ebMn_NdwDrdDwSu-ObfTupuXqumzO392I/edit#slide=id.p24

Because it's the end of the activity. It indicated that when toy click next, something different is going to happen then what happened last time you clicked it.

Please close if that makes sense or comment otherwise.

**Comment by maryohagan** [comment]
OK that's fine
