### ISSUE TITLE
In app print buttons?

### ISSUE THREAD

**Issue by grgcnnr** [beak-lab/swell#94]
re:  https://docs.google.com/presentation/d/1m_iCCSA1x1ebMn_NdwDrdDwSu-ObfTupuXqumzO392I/edit#slide=id.p26

I've never seen a print button in app before? Can you explain how this would work and why doing through the app is a good idea - rather than through a website / email.

**Comment by maryohagan** [comment]
OK what's the best way for someone to print out their activity or resources? To email them to myself? How would you indicated that on the app? What's difficult about printing from an app if you have a remote printer connection?

**Comment by grgcnnr** [comment]
Nothing is difficult about printing from the app if you have a remote printer connection.

2 things:

I'm willing to be that you're one of a very few people who do, (I'd like to see some numbers on how many people do print from phones) I don't even know how & I'd consider myself a phone power user.

The format that the activities are presented on the phone are probably not so good for paper. We'd have to bundle paper versions into the app.
/
Would the printed out activity be an empty worksheet or a summary of the work they had just done?

**Comment by maryohagan** [comment]
There needs to be the facility to print out the completed activities as well as the paper forms and resources. That could be done through emailing it to yourself and printing of a PC I guess. I print of my phone and assume it will get more common. At the moment we could just settle for a two step option. Anyway the button I suggested is just a place holder but we'll need to consider this issue more carefully when the real thing is being built.

**Comment by grgcnnr** [comment]
My  instincts are against in app printing as part of the ui landscape

**Comment by maryohagan** [comment]
OK - is there an easy way to show a route to printing out your own activity. If not just leave it for now.

**Comment by grgcnnr** [comment]
We can definitely do something.

**Comment by maryohagan** [comment]
Thanks
